### ISSUE TITLE
Sharing snippets doesn't work anymore (again)

### ISSUE THREAD

**Issue by Airblader** [moroshko/rxviz#13] opened 2018-02-06 18:02 UTC
My snippets all mysteriously disappeared, despite creating them after #12. And as of now, clicking the share button results in a "Failed" status.

This is really quite annoying – after #12 I had to recreate a couple dozen snippets for a presentation and now they're all gone again. :-( Why not just base64 encode the code + time window instead of storing the snippet in the backend?

**Comment by moroshko** [comment] 2018-02-07 03:07
I'm sorry to hear it caused you a trouble.
Looks like the https certificate has expired for the api.
I renewed it, and it seems ok now.
I need to automate the renewal process.
I'll think about your idea of base64.

**Comment by henry-alakazhang** [comment] 2018-07-30 06:44
Hey, it looks like this is occurring again (caused by the same thing)

**Comment by moroshko** [comment] 2018-07-30 07:00
Sorry about that. Fixed now.

**Closed by moroshko** 2018-07-30 07:00 UTC
